package com.idyll.mutualcomm.event;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mCRecordDataDaoConfig;

    private final MCRecordDataDao mCRecordDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mCRecordDataDaoConfig = daoConfigMap.get(MCRecordDataDao.class).clone();
        mCRecordDataDaoConfig.initIdentityScope(type);

        mCRecordDataDao = new MCRecordDataDao(mCRecordDataDaoConfig, this);

        registerDao(MCRecordData.class, mCRecordDataDao);
    }
    
    public void clear() {
        mCRecordDataDaoConfig.getIdentityScope().clear();
    }

    public MCRecordDataDao getMCRecordDataDao() {
        return mCRecordDataDao;
    }

}
