package com.idyll.mutualcomm.event;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "MCRECORD_DATA".
 */
public class MCRecordData implements Parcelable {
    
    /**
     * 还未提交
     */
    public static final int STATE_NOT_COMMIT = 0;
    /**
     * 已经提交
     */
    public static final int STATE_COMMITED = 1;
    /**
     * 请求成功
     */
    public static final int STATE_SUCCESS = 2;
    /**
     * 请求失败，需要重新提交
     */
    public static final int STATE_FAILED = 3;
    /**
     * 标记需要撤销
     */
    public static final int STATE_UNDO = 4;
    /** Not-null value. */
    private String _id;
    private String event_detail;
    private String match_id;
    private String team_id;
    private String player_id;
    private String code;
    private String position;
    private String event_location;
    private String event_mode;
    private String has_assist;
    private String client_event_id;
    private String client_started_at;
    private String client_ended_at;
    private String client_match_clock;
    private String state;

    public MCRecordData() {
    }

    public MCRecordData(String _id) {
        this._id = _id;
    }

    public MCRecordData(String _id, String event_detail, String match_id, String team_id, String player_id, String code, String position, String event_location, String event_mode, String has_assist, String client_event_id, String client_started_at, String client_ended_at, String client_match_clock, String state) {
        this._id = _id;
        this.event_detail = event_detail;
        this.match_id = match_id;
        this.team_id = team_id;
        this.player_id = player_id;
        this.code = code;
        this.position = position;
        this.event_location = event_location;
        this.event_mode = event_mode;
        this.has_assist = has_assist;
        this.client_event_id = client_event_id;
        this.client_started_at = client_started_at;
        this.client_ended_at = client_ended_at;
        this.client_match_clock = client_match_clock;
        this.state = state;
    }

    /** Not-null value. */
    public String get_id() {
        return _id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void set_id(String _id) {
        this._id = _id;
    }

    public String getEvent_detail() {
        return event_detail;
    }

    public void setEvent_detail(String event_detail) {
        this.event_detail = event_detail;
    }

    public String getMatch_id() {
        return match_id;
    }

    public void setMatch_id(String match_id) {
        this.match_id = match_id;
    }

    public String getTeam_id() {
        return team_id;
    }

    public void setTeam_id(String team_id) {
        this.team_id = team_id;
    }

    public String getPlayer_id() {
        return player_id;
    }

    public void setPlayer_id(String player_id) {
        this.player_id = player_id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getEvent_location() {
        return event_location;
    }

    public void setEvent_location(String event_location) {
        this.event_location = event_location;
    }

    public String getEvent_mode() {
        return event_mode;
    }

    public void setEvent_mode(String event_mode) {
        this.event_mode = event_mode;
    }

    public String getHas_assist() {
        return has_assist;
    }

    public void setHas_assist(String has_assist) {
        this.has_assist = has_assist;
    }

    public String getClient_event_id() {
        return client_event_id;
    }

    public void setClient_event_id(String client_event_id) {
        this.client_event_id = client_event_id;
    }

    public String getClient_started_at() {
        return client_started_at;
    }

    public void setClient_started_at(String client_started_at) {
        this.client_started_at = client_started_at;
    }

    public String getClient_ended_at() {
        return client_ended_at;
    }

    public void setClient_ended_at(String client_ended_at) {
        this.client_ended_at = client_ended_at;
    }

    public String getClient_match_clock() {
        return client_match_clock;
    }

    public void setClient_match_clock(String client_match_clock) {
        this.client_match_clock = client_match_clock;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this._id);
        dest.writeString(this.event_detail);
        dest.writeString(this.match_id);
        dest.writeString(this.team_id);
        dest.writeString(this.player_id);
        dest.writeString(this.code);
        dest.writeString(this.position);
        dest.writeString(this.event_location);
        dest.writeString(this.event_mode);
        dest.writeString(this.has_assist);
        dest.writeString(this.client_event_id);
        dest.writeString(this.client_started_at);
        dest.writeString(this.client_ended_at);
        dest.writeString(this.client_match_clock);
        dest.writeString(this.state);
    }

    protected MCRecordData(Parcel in) {
        this._id = in.readString();
        this.event_detail = in.readString();
        this.match_id = in.readString();
        this.team_id = in.readString();
        this.player_id = in.readString();
        this.code = in.readString();
        this.position = in.readString();
        this.event_location = in.readString();
        this.event_mode = in.readString();
        this.has_assist = in.readString();
        this.client_event_id = in.readString();
        this.client_started_at = in.readString();
        this.client_ended_at = in.readString();
        this.client_match_clock = in.readString();
        this.state = in.readString();
    }

    public static final Parcelable.Creator<MCRecordData> CREATOR = new Parcelable.Creator<MCRecordData>() {
        public MCRecordData createFromParcel(Parcel source) {
            return new MCRecordData(source);
        }

        public MCRecordData[] newArray(int size) {
            return new MCRecordData[size];
        }
    };
}
